#!/usr/bin/env python3
"""
Script de carga inicial de propiedades en SQLite.
Datos representativos del mercado inmobiliario de Isla de Margarita 2025-2026.
Basado en datos reales de portales: Viviun, Horizonte Group, RE/MAX 2 MIL,
RE/MAX Arena, Rent-A-House, YL Inmuebles, TuInmueble, Enclave Margarita.

Ejecutar: python scripts/seed_db.py
"""

import asyncio
import json
from pathlib import Path

import structlog

# Ajustar path para imports desde scripts/
import sys
sys.path.insert(0, str(Path(__file__).parent.parent))

from src.config import settings
from src.domain.models import Municipality, Property, PropertyStatus, PropertyType
from src.infrastructure.db import Database
from src.infrastructure.llm import LLMClient
from src.infrastructure.repositories import PropertyRepository

logger = structlog.get_logger()

# ============================================
# BASE DE DATOS — 45 PROPIEDADES
# ============================================
# 30 originales actualizadas + 15 nuevas basadas en listados reales 2025-2026.
# Precios, zonas y características reflejan el mercado actual.

SEED_PROPERTIES = [
    # === MANEIRO (Pampatar, Playa El Ángel, San Lorenzo, Apostadero) ===
    {
        "title": "Apartamento Vista al Mar Pampatar",
        "municipality": Municipality.MANEIRO,
        "zone": "Pampatar",
        "type": PropertyType.APARTAMENTO,
        "price_usd": 95000,
        "bedrooms": 2,
        "bathrooms": 2,
        "area_m2": 88,
        "description": "Moderno apartamento con vista panorámica al mar en Pampatar. Cocina equipada con tope de granito, sala con balcón, 2 habitaciones con aire acondicionado. Edificio con piscina, gimnasio y seguridad 24h. A 5 minutos de Playa El Ángel y centro comercial Sambil Margarita.",
        "features": ["vista al mar", "piscina", "gimnasio", "seguridad 24h", "aire acondicionado", "balcón", "cerca de Sambil"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-7955550",
        "contact_email": "ventas@inmueblesmargarita.com",
        "has_ocean_view": True,
        "is_furnished": False,
        "has_pool": True,
        "has_parking": True,
        "has_security": True,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": True,
        "is_new_construction": False,
        "has_balcony": True,
        "is_gated_community": True,
    },
    {
        "title": "Penthouse Duplex Obra Blanca Alaqua Plaza",
        "municipality": Municipality.MANEIRO,
        "zone": "Playa El Ángel",
        "type": PropertyType.PENTHOUSE,
        "price_usd": 290000,
        "bedrooms": 5,
        "bathrooms": 7,
        "area_m2": 435,
        "description": "Espectacular penthouse dúplex en obra blanca en Conjunto Residencial Alaqua Plaza, Torre 2000. 5 habitaciones, 7 baños, terrazas panorámicas con vista al mar. Oportunidad para personalización total. Zona exclusiva de Playa El Ángel.",
        "features": ["obra blanca", "vista al mar", "terraza panorámica", "zona exclusiva", "penthouse", "personalizable"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-7955550",
        "contact_email": "ventas@inmueblesmargarita.com",
        "has_ocean_view": True,
        "is_furnished": False,
        "has_pool": True,
        "has_parking": True,
        "has_security": True,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": False,
        "is_new_construction": True,
        "has_balcony": True,
        "is_gated_community": True,
    },
    {
        "title": "Apartamento Costasol 159m² con Terraza",
        "municipality": Municipality.MANEIRO,
        "zone": "Pampatar",
        "type": PropertyType.APARTAMENTO,
        "price_usd": 165000,
        "bedrooms": 4,
        "bathrooms": 4,
        "area_m2": 159,
        "description": "Hermoso y elegante apartamento en Conjunto Residencial Costasol. 159m² construcción + 110m² terraza. 3 habitaciones con baño, 1 habitación de servicio, cocina equipada con granito, jardín privado, 2 puestos de estacionamiento. Áreas sociales con piscina y vista al mar.",
        "features": ["terraza 110m²", "jardín privado", "vista al mar", "piscina", "2 estacionamientos", "servicio"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-7955550",
        "contact_email": "ventas@inmueblesmargarita.com",
        "has_ocean_view": True,
        "is_furnished": False,
        "has_pool": True,
        "has_parking": True,
        "has_security": True,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": False,
        "is_new_construction": False,
        "has_balcony": True,
        "is_gated_community": True,
    },
    {
        "title": "Casa Urbanización Paraíso Pampatar",
        "municipality": Municipality.MANEIRO,
        "zone": "Pampatar",
        "type": PropertyType.CASA,
        "price_usd": 170000,
        "bedrooms": 4,
        "bathrooms": 3,
        "area_m2": 210,
        "description": "Casa familiar en exclusiva urbanización Paraíso, Pampatar. 4 habitaciones, 3 baños, sala de doble altura, cocina moderna, jardín privado con parrillera. Cerca de Playa El Ángel y restaurantes de Pampatar. Ideal para familia o alquiler vacacional.",
        "features": ["jardín privado", "parrillera", "sala doble altura", "cerca de playa", "urbanización cerrada"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-7955550",
        "contact_email": "ventas@inmueblesmargarita.com",
        "has_ocean_view": False,
        "is_furnished": False,
        "has_pool": False,
        "has_parking": True,
        "has_security": True,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": False,
        "is_new_construction": False,
        "has_balcony": False,
        "is_gated_community": True,
    },
    {
        "title": "Terreno Playa El Ángel 11,106m²",
        "municipality": Municipality.MANEIRO,
        "zone": "Playa El Ángel",
        "type": PropertyType.TERRENO,
        "price_usd": 4000000,
        "bedrooms": None,
        "bathrooms": None,
        "area_m2": 11106,
        "description": "Terreno extenso de 11,106m² en Paraíso 1, Pampatar. Ideal para desarrollo residencial o comercial. Zona de alta plusvalía cerca de Playa El Ángel. Todos los servicios disponibles. Oportunidad de inversión a largo plazo.",
        "features": ["11,106m²", "desarrollo", "plusvalía", "servicios disponibles", "zona exclusiva"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-7955550",
        "contact_email": "ventas@inmueblesmargarita.com",
        "has_ocean_view": True,
        "is_furnished": False,
        "has_pool": False,
        "has_parking": False,
        "has_security": False,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": False,
        "is_new_construction": False,
        "has_balcony": False,
        "is_gated_community": False,
    },
    # --- NUEVAS: MANEIRO ---
    {
        "title": "Apartamento Edificio Costa de Oro Playa El Ángel",
        "municipality": Municipality.MANEIRO,
        "zone": "Playa El Ángel",
        "type": PropertyType.APARTAMENTO,
        "price_usd": 150000,
        "bedrooms": 3,
        "bathrooms": 2,
        "area_m2": 125,
        "description": "Apartamento de lujo en Edificio Costa de Oro, Playa El Ángel. 3 habitaciones, 2 baños, cocina equipada con granito, sala-comedor con balcón y vista al mar. Edificio con piscina, gimnasio, seguridad 24h y 2 puestos de estacionamiento. Zona exclusiva de alta plusvalía.",
        "features": ["vista al mar", "piscina", "gimnasio", "seguridad 24h", "2 estacionamientos", "granito"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-7955550",
        "contact_email": "ventas@inmueblesmargarita.com",
        "has_ocean_view": True,
        "is_furnished": False,
        "has_pool": True,
        "has_parking": True,
        "has_security": True,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": True,
        "is_new_construction": False,
        "has_balcony": True,
        "is_gated_community": True,
    },
    {
        "title": "Local Comercial Apostadero Pampatar",
        "municipality": Municipality.MANEIRO,
        "zone": "Apostadero",
        "type": PropertyType.LOCAL_COMERCIAL,
        "price_usd": 70000,
        "bedrooms": None,
        "bathrooms": 2,
        "area_m2": 215,
        "description": "Local comercial de 215m² en Apostadero, Pampatar. 2 oficinas independientes, baño, área de almacén, estacionamiento para 3 vehículos. Zona comercial en crecimiento cerca de Sambil Margarita. Ideal para oficina, consultorio o retail.",
        "features": ["2 oficinas", "almacén", "3 estacionamientos", "zona comercial", "cerca de Sambil"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-7955550",
        "contact_email": "ventas@inmueblesmargarita.com",
        "has_ocean_view": False,
        "is_furnished": False,
        "has_pool": False,
        "has_parking": True,
        "has_security": False,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": False,
        "is_new_construction": False,
        "has_balcony": False,
        "is_gated_community": False,
    },
    {
        "title": "Posada San Lorenzo 17 Habitaciones",
        "municipality": Municipality.MANEIRO,
        "zone": "San Lorenzo",
        "type": PropertyType.QUINTA,
        "price_usd": 1300000,
        "bedrooms": 17,
        "bathrooms": 18,
        "area_m2": 850,
        "description": "Posada operativa de 17 habitaciones en San Lorenzo, al lado del Sambil Margarita. 850m² construcción en terreno de 2,500m². Piscina, restaurante, estacionamiento para 20 vehículos. Ocupación constante todo el año. Negocio turnkey con flujo de caja inmediato.",
        "features": ["17 habitaciones", "piscina", "restaurante", "20 estacionamientos", "turnkey", "ocupación alta"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-7955550",
        "contact_email": "ventas@inmueblesmargarita.com",
        "has_ocean_view": False,
        "is_furnished": True,
        "has_pool": True,
        "has_parking": True,
        "has_security": True,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": True,
        "is_new_construction": False,
        "has_balcony": False,
        "is_gated_community": True,
    },

    # === MARIÑO (Porlamar, Costa Azul, Sabanamar, Playa Moreno, Los Robles) ===
    {
        "title": "Apartamento Ejecutivo Porlamar Centro",
        "municipality": Municipality.MARINO,
        "zone": "Porlamar Centro",
        "type": PropertyType.APARTAMENTO,
        "price_usd": 65000,
        "bedrooms": 2,
        "bathrooms": 2,
        "area_m2": 75,
        "description": "Apartamento ejecutivo en el corazón de Porlamar. 2 habitaciones, 2 baños, cocina equipada, sala-comedor. Cerca de Sambil Margarita, bancos, restaurantes y centros comerciales. Ideal para residencia o inversión de alquiler largo plazo. Edificio con ascensor y seguridad.",
        "features": ["centro de Porlamar", "cerca de Sambil", "ascensor", "seguridad", "ejecutivo"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-1234567",
        "contact_email": "porlamar@horizontegroupmgta.com",
        "has_ocean_view": False,
        "is_furnished": False,
        "has_pool": False,
        "has_parking": False,
        "has_security": True,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": False,
        "is_new_construction": False,
        "has_balcony": False,
        "is_gated_community": False,
    },
    {
        "title": "Apartamento Carimar Club 56m² Sabanamar",
        "municipality": Municipality.MARINO,
        "zone": "Sabanamar",
        "type": PropertyType.APARTAMENTO,
        "price_usd": 51000,
        "bedrooms": 1,
        "bathrooms": 1,
        "area_m2": 56,
        "description": "Acogedor apartamento de 56m² en Edificio Carimar Club, Sabanamar. 1 habitación, 1 baño, cocina americana, balcón con vista a áreas verdes. Edificio con piscina, parque infantil y estacionamiento. A 10 minutos del centro de Porlamar y Playa Moreno.",
        "features": ["piscina", "parque infantil", "balcón", "cocina americana", "áreas verdes"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-1234567",
        "contact_email": "porlamar@horizontegroupmgta.com",
        "has_ocean_view": False,
        "is_furnished": False,
        "has_pool": True,
        "has_parking": True,
        "has_security": True,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": False,
        "is_new_construction": False,
        "has_balcony": True,
        "is_gated_community": False,
    },
    {
        "title": "Casa Avenida Guaiquerí Sabanamar 450m²",
        "municipality": Municipality.MARINO,
        "zone": "Sabanamar",
        "type": PropertyType.CASA,
        "price_usd": 290000,
        "bedrooms": 5,
        "bathrooms": 6,
        "area_m2": 450,
        "description": "Imponente casa de 450m² en Avenida Guaiquerí, Sabanamar. 5 habitaciones, 6 baños, sala de cine, cocina gourmet, jardín tropical con piscina. Garaje para 4 vehículos. Ideal para familia grande o boutique hotel. Zona residencial consolidada.",
        "features": ["sala de cine", "cocina gourmet", "piscina", "jardín tropical", "garaje 4 autos", "boutique hotel"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-1234567",
        "contact_email": "porlamar@horizontegroupmgta.com",
        "has_ocean_view": False,
        "is_furnished": False,
        "has_pool": True,
        "has_parking": True,
        "has_security": True,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": False,
        "is_new_construction": False,
        "has_balcony": False,
        "is_gated_community": True,
    },
    {
        "title": "Apartamento Costa Azul 220m² Los Sauces",
        "municipality": Municipality.MARINO,
        "zone": "Costa Azul",
        "type": PropertyType.APARTAMENTO,
        "price_usd": 90000,
        "bedrooms": 4,
        "bathrooms": 3,
        "area_m2": 220,
        "description": "Amplio apartamento de 220m² en Conjunto Residencial Los Sauces, Urbanización Costa Azul. 4 habitaciones, 3 baños, 2 balcones integrados, 4 unidades de aire acondicionado. Vista lejana al mar. 4 tanques de agua de 600L c/u. Remodelado y amoblado.",
        "features": ["220m²", "vista al mar", "4 aires acondicionados", "remodelado", "amoblado", "2 balcones"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-1234567",
        "contact_email": "porlamar@horizontegroupmgta.com",
        "has_ocean_view": True,
        "is_furnished": True,
        "has_pool": False,
        "has_parking": True,
        "has_security": True,
        "has_generator": False,
        "has_water_tank": True,
        "has_ac": True,
        "is_new_construction": False,
        "has_balcony": True,
        "is_gated_community": True,
    },
    {
        "title": "Apartamento Playa Moreno 84m² Primer Piso",
        "municipality": Municipality.MARINO,
        "zone": "Playa Moreno",
        "type": PropertyType.APARTAMENTO,
        "price_usd": 120000,
        "bedrooms": 2,
        "bathrooms": 2,
        "area_m2": 84,
        "description": "Hermoso apartamento de 84m² en primer piso, Playa Moreno. Cocina moderna con tope de granito, 2 habitaciones, 2 baños, terraza fresca con vista a piscina. Tanque de 500L, calentador, aire acondicionado de 5 toneladas. Áreas sociales con jardines.",
        "features": ["primer piso", "vista a piscina", "terraza", "cocina moderna", "granito", "Playa Moreno"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-1234567",
        "contact_email": "porlamar@horizontegroupmgta.com",
        "has_ocean_view": False,
        "is_furnished": False,
        "has_pool": True,
        "has_parking": True,
        "has_security": True,
        "has_generator": False,
        "has_water_tank": True,
        "has_ac": True,
        "is_new_construction": False,
        "has_balcony": True,
        "is_gated_community": True,
    },
    # --- NUEVAS: MARIÑO ---
    {
        "title": "Apartamento Resd. Los Sauces Costa Azul 75m²",
        "municipality": Municipality.MARINO,
        "zone": "Costa Azul",
        "type": PropertyType.APARTAMENTO,
        "price_usd": 62700,
        "bedrooms": 2,
        "bathrooms": 2,
        "area_m2": 75,
        "description": "Apartamento de 75m² en Residencias Los Sauces, Costa Azul. 2 habitaciones, 2 baños, cocina equipada, sala-comedor, balcón con vista a áreas verdes. Edificio con piscina, parque infantil y estacionamiento. Zona residencial consolidada cerca de Playa Moreno.",
        "features": ["piscina", "parque infantil", "balcón", "cocina equipada", "áreas verdes", "Costa Azul"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-1234567",
        "contact_email": "porlamar@horizontegroupmgta.com",
        "has_ocean_view": False,
        "is_furnished": False,
        "has_pool": True,
        "has_parking": True,
        "has_security": True,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": False,
        "is_new_construction": False,
        "has_balcony": True,
        "is_gated_community": True,
    },
    {
        "title": "Local Comercial Los Robles Porlamar",
        "municipality": Municipality.MARINO,
        "zone": "Los Robles",
        "type": PropertyType.LOCAL_COMERCIAL,
        "price_usd": 105000,
        "bedrooms": None,
        "bathrooms": 2,
        "area_m2": 180,
        "description": "Local comercial de 180m² en Los Robles, Porlamar. 2 baños, área de oficina, almacén, estacionamiento para 4 vehículos. Zona comercial de alto tráfico cerca de avenidas principales. Ideal para retail, restaurante o showroom.",
        "features": ["oficina", "almacén", "4 estacionamientos", "zona comercial", "alto tráfico"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-1234567",
        "contact_email": "porlamar@horizontegroupmgta.com",
        "has_ocean_view": False,
        "is_furnished": False,
        "has_pool": False,
        "has_parking": True,
        "has_security": False,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": False,
        "is_new_construction": False,
        "has_balcony": False,
        "is_gated_community": False,
    },
    {
        "title": "Townhouse Lomas de Encanto Guatamare",
        "municipality": Municipality.MARINO,
        "zone": "Guatamare",
        "type": PropertyType.TOWNHOUSE,
        "price_usd": 170000,
        "bedrooms": 4,
        "bathrooms": 4,
        "area_m2": 182,
        "description": "Townhouse de 182m² en Lomas de Encanto, Guatamare. 4 habitaciones, 4 baños, sala de doble altura, cocina moderna, jardín privado con piscina. Garaje para 2 vehículos. Urbanización cerrada con seguridad 24h. Ideal para familia.",
        "features": ["piscina privada", "jardín privado", "sala doble altura", "garaje 2 autos", "urbanización cerrada"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-1234567",
        "contact_email": "porlamar@horizontegroupmgta.com",
        "has_ocean_view": False,
        "is_furnished": False,
        "has_pool": True,
        "has_parking": True,
        "has_security": True,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": False,
        "is_new_construction": False,
        "has_balcony": False,
        "is_gated_community": True,
    },

    # === ANTOLÍN DEL CAMPO (Playa El Agua, La Mira, El Yaque) ===
    {
        "title": "Penthouse de Lujo Playa El Agua",
        "municipality": Municipality.ANTOLIN_DEL_CAMPO,
        "zone": "Playa El Agua",
        "type": PropertyType.PENTHOUSE,
        "price_usd": 180000,
        "bedrooms": 3,
        "bathrooms": 3,
        "area_m2": 154,
        "description": "Espectacular penthouse de 154m² + 75m² terraza cubierta en Playa El Agua. 2 niveles, 3 habitaciones, 3 baños. Vista al mar y al anclaje de yates. 2 apartamentos de 1 habitación en planta baja generan $12,000/año en alquiler turístico. Inversión con flujo de caja inmediato.",
        "features": ["penthouse", "terraza 75m²", "vista al mar", "2 apartamentos rentables", "alquiler turístico", "yates"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-9876543",
        "contact_email": "playa@islamargaritaestates.com",
        "has_ocean_view": True,
        "is_furnished": False,
        "has_pool": False,
        "has_parking": True,
        "has_security": True,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": True,
        "is_new_construction": False,
        "has_balcony": True,
        "is_gated_community": True,
    },
    {
        "title": "Hotel Bed & Breakfast Playa El Agua 20 Hab",
        "municipality": Municipality.ANTOLIN_DEL_CAMPO,
        "zone": "Playa El Agua",
        "type": PropertyType.LOCAL,
        "price_usd": 600000,
        "bedrooms": 20,
        "bathrooms": 22,
        "area_m2": 2200,
        "description": "Hotel Bed & Breakfast operativo en Playa El Agua, a 800m de la playa. 20 habitaciones de 34m² cada una, 22 baños, restaurante tipo churuata, piscina de 120,000L. Terreno de 2,200m², construcción 960m². Ocupación constante todo el año. Negocio turnkey.",
        "features": ["hotel operativo", "20 habitaciones", "restaurante", "piscina", "turnkey", "800m de playa"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-9876543",
        "contact_email": "playa@islamargaritaestates.com",
        "has_ocean_view": False,
        "is_furnished": True,
        "has_pool": True,
        "has_parking": True,
        "has_security": True,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": True,
        "is_new_construction": False,
        "has_balcony": False,
        "is_gated_community": True,
    },
    {
        "title": "Casa Puerto Real Playa El Agua 155m²",
        "municipality": Municipality.ANTOLIN_DEL_CAMPO,
        "zone": "Playa El Agua",
        "type": PropertyType.CASA,
        "price_usd": 94000,
        "bedrooms": 3,
        "bathrooms": 2,
        "area_m2": 155,
        "description": "Casa en exclusiva comunidad cerrada Puerto Real, Playa El Agua. 155m² construcción en 603m² terreno. 3 habitaciones, 2 baños, amoblada, garaje cerrado. Seguridad 24h, acceso directo a playa. Ideal para vacaciones o alquiler vacacional de lujo.",
        "features": ["comunidad cerrada", "amoblada", "seguridad 24h", "acceso a playa", "garaje cerrado"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-9876543",
        "contact_email": "playa@islamargaritaestates.com",
        "has_ocean_view": False,
        "is_furnished": True,
        "has_pool": False,
        "has_parking": True,
        "has_security": True,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": True,
        "is_new_construction": False,
        "has_balcony": False,
        "is_gated_community": True,
    },
    {
        "title": "Villa La Mira 250m² Cerca de Playa",
        "municipality": Municipality.ANTOLIN_DEL_CAMPO,
        "zone": "La Mira",
        "type": PropertyType.CASA,
        "price_usd": 130000,
        "bedrooms": 4,
        "bathrooms": 2,
        "area_m2": 250,
        "description": "Villa de 250m² en La Mira, cerca de Playa El Agua. Dividida en 2 apartamentos independientes de 2 habitaciones cada uno. Terreno amplio con jardín tropical. Ideal para alquiler vacacional dual o residencia multifamiliar. A 5 minutos de la playa.",
        "features": ["2 apartamentos", "jardín tropical", "alquiler dual", "multifamiliar", "cerca de playa"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-9876543",
        "contact_email": "playa@islamargaritaestates.com",
        "has_ocean_view": False,
        "is_furnished": False,
        "has_pool": False,
        "has_parking": True,
        "has_security": False,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": False,
        "is_new_construction": False,
        "has_balcony": False,
        "is_gated_community": False,
    },
    {
        "title": "Terreno 25 hectáreas Playa El Agua",
        "municipality": Municipality.ANTOLIN_DEL_CAMPO,
        "zone": "Playa El Agua",
        "type": PropertyType.TERRENO,
        "price_usd": 25000,
        "bedrooms": None,
        "bathrooms": None,
        "area_m2": 250000,
        "description": "Terreno de 25 hectáreas a 200m de Playa El Agua. Varios árboles frutales (mango, coco). Incluye pequeña casa de 2 habitaciones que necesita renovación. Ideal para desarrollo turístico, eco-lodge o finca. Acceso directo por carretera principal.",
        "features": ["25 hectáreas", "200m de playa", "árboles frutales", "desarrollo turístico", "eco-lodge"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-9876543",
        "contact_email": "playa@islamargaritaestates.com",
        "has_ocean_view": False,
        "is_furnished": False,
        "has_pool": False,
        "has_parking": False,
        "has_security": False,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": False,
        "is_new_construction": False,
        "has_balcony": False,
        "is_gated_community": False,
    },
    # --- NUEVAS: ANTOLÍN DEL CAMPO ---
    {
        "title": "Townhouse El Yaque 3 Hab 2.5 Baños",
        "municipality": Municipality.ANTOLIN_DEL_CAMPO,
        "zone": "El Yaque",
        "type": PropertyType.TOWNHOUSE,
        "price_usd": 85000,
        "bedrooms": 3,
        "bathrooms": 3,
        "area_m2": 110,
        "description": "Townhouse de 110m² en El Yaque, a 5 minutos de la playa. 3 habitaciones, 2.5 baños, sala-comedor, cocina equipada, terraza con vista al mar. Urbanización cerrada con piscina y seguridad 24h. Ideal para vacaciones o alquiler turístico.",
        "features": ["vista al mar", "terraza", "piscina", "seguridad 24h", "cerca de playa", "El Yaque"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-9876543",
        "contact_email": "playa@islamargaritaestates.com",
        "has_ocean_view": True,
        "is_furnished": False,
        "has_pool": True,
        "has_parking": True,
        "has_security": True,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": True,
        "is_new_construction": True,
        "has_balcony": True,
        "is_gated_community": True,
    },
    {
        "title": "Casa Playa El Agua 170m² 5 Hab",
        "municipality": Municipality.ANTOLIN_DEL_CAMPO,
        "zone": "Playa El Agua",
        "type": PropertyType.CASA,
        "price_usd": 210000,
        "bedrooms": 5,
        "bathrooms": 3,
        "area_m2": 170,
        "description": "Casa de 170m² en Playa El Agua, a 300m de la playa. 5 habitaciones, 3 baños, piscina privada, jardín tropical, terraza con parrillera. Amoblada, aire acondicionado en todas las habitaciones. Ideal para alquiler vacacional o residencia grande.",
        "features": ["piscina privada", "jardín tropical", "parrillera", "amoblada", "cerca de playa"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-9876543",
        "contact_email": "playa@islamargaritaestates.com",
        "has_ocean_view": False,
        "is_furnished": True,
        "has_pool": True,
        "has_parking": True,
        "has_security": True,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": True,
        "is_new_construction": False,
        "has_balcony": True,
        "is_gated_community": True,
    },

    # === ARISMENDI (La Asunción, Juan Griego, El Tirano, La Guardia) ===
    {
        "title": "Casa Colonial La Asunción",
        "municipality": Municipality.ARISMENDI,
        "zone": "La Asunción",
        "type": PropertyType.CASA,
        "price_usd": 45000,
        "bedrooms": 3,
        "bathrooms": 2,
        "area_m2": 120,
        "description": "Encantadora casa colonial en el casco histórico de La Asunción. 3 habitaciones, 2 baños, patio interior con fuente, techos de madera original. A 2 cuadras de la Catedral y Plaza Bolívar. Ideal para boutique hotel o residencia con carácter histórico.",
        "features": ["colonial", "casco histórico", "patio interior", "techos de madera", "cerca de Catedral"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-5551212",
        "contact_email": "historico@arismendirealty.com",
        "has_ocean_view": False,
        "is_furnished": False,
        "has_pool": False,
        "has_parking": False,
        "has_security": False,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": False,
        "is_new_construction": False,
        "has_balcony": False,
        "is_gated_community": False,
    },
    {
        "title": "Casa Familiar Juan Griego",
        "municipality": Municipality.ARISMENDI,
        "zone": "Juan Griego",
        "type": PropertyType.CASA,
        "price_usd": 55000,
        "bedrooms": 3,
        "bathrooms": 2,
        "area_m2": 140,
        "description": "Casa familiar de 140m² en Juan Griego. 3 habitaciones, 2 baños, sala-comedor, cocina equipada. Terreno de 300m² con jardín y parrillera. Cerca de Playa Caribe y del centro de Juan Griego. Precio accesible para familia local.",
        "features": ["precio accesible", "jardín", "parrillera", "cerca de Playa Caribe", "familiar"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-5551212",
        "contact_email": "historico@arismendirealty.com",
        "has_ocean_view": False,
        "is_furnished": False,
        "has_pool": False,
        "has_parking": True,
        "has_security": False,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": False,
        "is_new_construction": False,
        "has_balcony": False,
        "is_gated_community": False,
    },
    {
        "title": "Apartamento Estudio Juan Griego 2h/2b",
        "municipality": Municipality.ARISMENDI,
        "zone": "Juan Griego",
        "type": PropertyType.APARTAMENTO,
        "price_usd": 35000,
        "bedrooms": 2,
        "bathrooms": 2,
        "area_m2": 55,
        "description": "Apartamento tipo estudio en Juan Griego. 2 habitaciones, 2 baños, cocina americana, balcón. Edificio nuevo con ascensor. Ideal para pareja joven o inversión de alquiler. A 8 minutos caminando del malecón de Juan Griego.",
        "features": ["estudio", "edificio nuevo", "ascensor", "cerca del malecón", "inversión"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-5551212",
        "contact_email": "historico@arismendirealty.com",
        "has_ocean_view": False,
        "is_furnished": False,
        "has_pool": False,
        "has_parking": True,
        "has_security": True,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": False,
        "is_new_construction": True,
        "has_balcony": True,
        "is_gated_community": False,
    },
    {
        "title": "Casa Quinta El Tirano 4 Hab 3 Baños",
        "municipality": Municipality.ARISMENDI,
        "zone": "El Tirano",
        "type": PropertyType.CASA,
        "price_usd": 110000,
        "bedrooms": 4,
        "bathrooms": 3,
        "area_m2": 280,
        "description": "Casa quinta de 280m² en El Tirano. 4 habitaciones, 3 baños, piscina privada, jardín amplio con árboles frutales. Garaje para 3 vehículos. Zona tranquila con vista a la montaña. Ideal para retiro o fin de semana.",
        "features": ["piscina privada", "jardín amplio", "garaje 3 autos", "vista a montaña", "retiro"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-5551212",
        "contact_email": "historico@arismendirealty.com",
        "has_ocean_view": False,
        "is_furnished": False,
        "has_pool": True,
        "has_parking": True,
        "has_security": False,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": False,
        "is_new_construction": False,
        "has_balcony": False,
        "is_gated_community": False,
    },
    {
        "title": "Terreno La Guardia 1,236m²",
        "municipality": Municipality.ARISMENDI,
        "zone": "La Guardia",
        "type": PropertyType.TERRENO,
        "price_usd": 55000,
        "bedrooms": None,
        "bathrooms": None,
        "area_m2": 1236,
        "description": "Terreno de 1,236m² en La Guardia, cerca del aeropuerto Santiago Mariño. Plano, con servicios en borde. Ideal para construcción residencial o comercial. Zona en crecimiento con nuevos desarrollos. Excelente plusvalía proyectada.",
        "features": ["1,236m²", "cerca de aeropuerto", "plano", "servicios en borde", "plusvalía"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-5551212",
        "contact_email": "historico@arismendirealty.com",
        "has_ocean_view": False,
        "is_furnished": False,
        "has_pool": False,
        "has_parking": False,
        "has_security": False,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": False,
        "is_new_construction": False,
        "has_balcony": False,
        "is_gated_community": False,
    },
    # --- NUEVAS: ARISMENDI ---
    {
        "title": "Casa La Asunción 3 Hab 2 Baños",
        "municipality": Municipality.ARISMENDI,
        "zone": "La Asunción",
        "type": PropertyType.CASA,
        "price_usd": 55000,
        "bedrooms": 3,
        "bathrooms": 2,
        "area_m2": 135,
        "description": "Casa de 135m² en La Asunción, cerca del casco histórico. 3 habitaciones, 2 baños, sala-comedor, cocina equipada, patio interior. Terreno de 250m². A 3 cuadras de la Catedral. Ideal para residencia o pequeño boutique hotel.",
        "features": ["casco histórico", "patio interior", "cerca de Catedral", "terreno 250m²", "boutique hotel"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-5551212",
        "contact_email": "historico@arismendirealty.com",
        "has_ocean_view": False,
        "is_furnished": False,
        "has_pool": False,
        "has_parking": True,
        "has_security": False,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": False,
        "is_new_construction": False,
        "has_balcony": False,
        "is_gated_community": False,
    },
    {
        "title": "Casa El Maco Los Veleros 133m²",
        "municipality": Municipality.ARISMENDI,
        "zone": "Los Veleros",
        "type": PropertyType.CASA,
        "price_usd": 16000,
        "bedrooms": 2,
        "bathrooms": 2,
        "area_m2": 133,
        "description": "Casa de 133m² en El Maco, Los Veleros, Juan Griego. 2 habitaciones, 2 baños, sala-comedor, cocina equipada. Terreno de 200m² con jardín. Precio accesible para familia local o inversión de alquiler. A 10 minutos del malecón.",
        "features": ["precio accesible", "jardín", "inversión", "cerca del malecón", "Los Veleros"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-5551212",
        "contact_email": "historico@arismendirealty.com",
        "has_ocean_view": False,
        "is_furnished": False,
        "has_pool": False,
        "has_parking": True,
        "has_security": False,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": False,
        "is_new_construction": False,
        "has_balcony": False,
        "is_gated_community": False,
    },

    # === GÓMEZ (Playa Caribe, Guacuco) ===
    {
        "title": "Terreno Playa Caribe 900m² con Permiso",
        "municipality": Municipality.GOMEZ,
        "zone": "Playa Caribe",
        "type": PropertyType.TERRENO,
        "price_usd": 47000,
        "bedrooms": None,
        "bathrooms": None,
        "area_m2": 900,
        "description": "Terreno de 900m² en Playa Caribe con permiso para edificio de 3 plantas. 200m de playa privada, bahía apta para botes. Servicios en borde. Opción de comprar lotes adyacentes. Ideal para casa de playa o pequeño hotel boutique.",
        "features": ["900m²", "playa privada", "permiso 3 plantas", "bahía para botes", "lotes adyacentes"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-3334444",
        "contact_email": "caribe@gomerealty.com",
        "has_ocean_view": True,
        "is_furnished": False,
        "has_pool": False,
        "has_parking": False,
        "has_security": False,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": False,
        "is_new_construction": False,
        "has_balcony": False,
        "is_gated_community": False,
    },
    {
        "title": "Apartamento Guacuco Beach 73m²",
        "municipality": Municipality.GOMEZ,
        "zone": "Guacuco",
        "type": PropertyType.APARTAMENTO,
        "price_usd": 85000,
        "bedrooms": 3,
        "bathrooms": 1,
        "area_m2": 73,
        "description": "Apartamento de 73m² en Edificio Los Peregrinos, Guacuco. 3 habitaciones, 1.5 baños, cocina equipada. Conjunto con zona comercial, residencial y piscina. A 400m de Playa Guacuco. Ideal para familia o alquiler vacacional.",
        "features": ["zona comercial", "piscina", "400m de playa", "cocina equipada", "Guacuco"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-3334444",
        "contact_email": "caribe@gomerealty.com",
        "has_ocean_view": False,
        "is_furnished": False,
        "has_pool": True,
        "has_parking": True,
        "has_security": True,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": False,
        "is_new_construction": False,
        "has_balcony": True,
        "is_gated_community": False,
    },
    {
        "title": "Villa Guacuco Tropical 155m²",
        "municipality": Municipality.GOMEZ,
        "zone": "Guacuco",
        "type": PropertyType.CASA,
        "price_usd": 69000,
        "bedrooms": 3,
        "bathrooms": 2,
        "area_m2": 155,
        "description": "Villa tropical de 155m² en Guacuco, a minutos de la playa. 3 habitaciones, 2 baños, jardín con palmeras, terraza con hamacas. Estilo caribeño auténtico. Ideal para casa vacacional o retiro tranquilo. Precio accesible para zona turística.",
        "features": ["estilo caribeño", "jardín con palmeras", "terraza", "hamacas", "precio accesible"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-3334444",
        "contact_email": "caribe@gomerealty.com",
        "has_ocean_view": False,
        "is_furnished": False,
        "has_pool": False,
        "has_parking": True,
        "has_security": False,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": False,
        "is_new_construction": False,
        "has_balcony": True,
        "is_gated_community": False,
    },
    {
        "title": "Condo Golden Sands Guacuco 70+ Unidades",
        "municipality": Municipality.GOMEZ,
        "zone": "Guacuco",
        "type": PropertyType.APARTAMENTO,
        "price_usd": 60000,
        "bedrooms": 2,
        "bathrooms": 2,
        "area_m2": 65,
        "description": "Nuevo proyecto residencial Golden Sands, a pasos de Playa Guacuco. Más de 70 unidades con acceso fácil a la playa desde $60,000. 2 habitaciones, 2 baños, balcón, áreas sociales. Ideal para inversión con plusvalía garantizada en zona emergente.",
        "features": ["nuevo proyecto", "70+ unidades", "acceso a playa", "plusvalía", "zona emergente"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-3334444",
        "contact_email": "caribe@gomerealty.com",
        "has_ocean_view": False,
        "is_furnished": False,
        "has_pool": True,
        "has_parking": True,
        "has_security": True,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": False,
        "is_new_construction": True,
        "has_balcony": True,
        "is_gated_community": True,
    },
    {
        "title": "Terreno con Vista La Guardia 1,592m²",
        "municipality": Municipality.GOMEZ,
        "zone": "La Guardia",
        "type": PropertyType.TERRENO,
        "price_usd": 30000,
        "bedrooms": None,
        "bathrooms": None,
        "area_m2": 1592,
        "description": "Terreno de 1,592m² en La Guardia con vista a la montaña y al valle. Plano, acceso por carretera asfaltada. Servicios a 200m. Ideal para casa de campo o finca de agroturismo. Zona tranquila, clima fresco.",
        "features": ["vista a montaña", "plano", "carretera asfaltada", "clima fresco", "agroturismo"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-3334444",
        "contact_email": "caribe@gomerealty.com",
        "has_ocean_view": False,
        "is_furnished": False,
        "has_pool": False,
        "has_parking": False,
        "has_security": False,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": False,
        "is_new_construction": False,
        "has_balcony": False,
        "is_gated_community": False,
    },
    # --- NUEVAS: GÓMEZ ---
    {
        "title": "Apartamento Terrazas de Guacuco Vista al Mar",
        "municipality": Municipality.GOMEZ,
        "zone": "Guacuco",
        "type": PropertyType.APARTAMENTO,
        "price_usd": 58000,
        "bedrooms": 2,
        "bathrooms": 1,
        "area_m2": 68,
        "description": "Apartamento de 68m² en Terrazas de Guacuco, con terraza y vista al mar. 2 habitaciones, 1 baño, cocina equipada, sala-comedor. Edificio con piscina y estacionamiento. A 500m de Playa Guacuco. Ideal para inversión vacacional.",
        "features": ["vista al mar", "terraza", "piscina", "500m de playa", "inversión vacacional"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-3334444",
        "contact_email": "caribe@gomerealty.com",
        "has_ocean_view": True,
        "is_furnished": False,
        "has_pool": True,
        "has_parking": True,
        "has_security": False,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": False,
        "is_new_construction": False,
        "has_balcony": True,
        "is_gated_community": False,
    },

    # === MARCANO (Playa Parguito, La Caranta) ===
    {
        "title": "Apartamento Playa Parguito 44m² Frente al Mar",
        "municipality": Municipality.MARCANO,
        "zone": "Playa Parguito",
        "type": PropertyType.APARTAMENTO,
        "price_usd": 65000,
        "bedrooms": 1,
        "bathrooms": 1,
        "area_m2": 44,
        "description": "Apartamento de 44m² frente al mar en Playa Parguito. 1 habitación, 1 baño, cocina/living/dining integrado, sofá cama doble. Amoblado, aire acondicionado, TV cable. Ventanas panorámicas con vista al mar y piscina. Acceso directo a playa.",
        "features": ["frente al mar", "amoblado", "vista panorámica", "acceso directo playa", "Playa Parguito"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-7778888",
        "contact_email": "parguito@marcanorealty.com",
        "has_ocean_view": True,
        "is_furnished": True,
        "has_pool": True,
        "has_parking": True,
        "has_security": True,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": True,
        "is_new_construction": False,
        "has_balcony": True,
        "is_gated_community": True,
    },
    {
        "title": "Condo Cimarron Suites 3 Hab 92m²",
        "municipality": Municipality.MARCANO,
        "zone": "Playa Parguito",
        "type": PropertyType.APARTAMENTO,
        "price_usd": 65000,
        "bedrooms": 3,
        "bathrooms": 2,
        "area_m2": 92,
        "description": "Condo en Cimarron Suites, probablemente la mejor propiedad frente al mar de la isla. 3 habitaciones, 2 baños, 2 piscinas, acceso directo a Playa Parguito, cancha de tenis, jardines tropicales. Seguridad 24h, estacionamiento subterráneo, ascensores. Ideal para vivir o vacacionar.",
        "features": ["2 piscinas", "cancha de tenis", "jardines tropicales", "seguridad 24h", "estacionamiento subterráneo"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-7778888",
        "contact_email": "parguito@marcanorealty.com",
        "has_ocean_view": True,
        "is_furnished": False,
        "has_pool": True,
        "has_parking": True,
        "has_security": True,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": True,
        "is_new_construction": False,
        "has_balcony": True,
        "is_gated_community": True,
    },
    {
        "title": "Casa Playa Parguito 540m² 2 Apartamentos",
        "municipality": Municipality.MARCANO,
        "zone": "Playa Parguito",
        "type": PropertyType.CASA,
        "price_usd": 98000,
        "bedrooms": 4,
        "bathrooms": 2,
        "area_m2": 180,
        "description": "Casa dividida en 2 apartamentos independientes de 2 habitaciones cada uno. Terreno de 540m² muy cerca de la playa con vista al mar. Posibilidad de construir más apartamentos, restaurante y piscina. Playa Parguito es una de las playas más populares de Margarita.",
        "features": ["2 apartamentos", "vista al mar", "terreno 540m²", "expandible", "playa popular"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-7778888",
        "contact_email": "parguito@marcanorealty.com",
        "has_ocean_view": True,
        "is_furnished": False,
        "has_pool": False,
        "has_parking": True,
        "has_security": False,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": False,
        "is_new_construction": False,
        "has_balcony": False,
        "is_gated_community": False,
    },
    {
        "title": "Apartamento La Caranta 70m² Vista al Mar",
        "municipality": Municipality.MARCANO,
        "zone": "La Caranta",
        "type": PropertyType.APARTAMENTO,
        "price_usd": 60000,
        "bedrooms": 1,
        "bathrooms": 2,
        "area_m2": 70,
        "description": "Encantador apartamento de 70m² con vista al mar Caribe en La Caranta. 1 habitación grande, 2 baños, balcón, lavadora/secadora, nevera, horno, aire acondicionado. 2 ventanas amplias con vista al océano. Cerca de casinos, restaurantes, supermercados, golf, marinas. A 20 minutos del aeropuerto.",
        "features": ["vista al Caribe", "balcón", "cerca de casinos", "golf", "marinas", "20min aeropuerto"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-7778888",
        "contact_email": "parguito@marcanorealty.com",
        "has_ocean_view": True,
        "is_furnished": True,
        "has_pool": False,
        "has_parking": True,
        "has_security": True,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": True,
        "is_new_construction": False,
        "has_balcony": True,
        "is_gated_community": True,
    },
    {
        "title": "Hotel 20 Hab Playa Parquito 50m de Playa",
        "municipality": Municipality.MARCANO,
        "zone": "Playa Parquito",
        "type": PropertyType.LOCAL,
        "price_usd": 390000,
        "bedrooms": 20,
        "bathrooms": 20,
        "area_m2": 1500,
        "description": "Hotel operativo de 20 habitaciones a 50m de Playa Parquito. Incluye restaurante, terraza rooftop con vista al mar. Setup turnkey listo para operar. Ocupación alta todo el año. Ideal para inversor hotelero que busca negocio funcionando desde el día 1.",
        "features": ["hotel operativo", "20 habitaciones", "restaurante", "rooftop", "turnkey", "50m de playa"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-7778888",
        "contact_email": "parguito@marcanorealty.com",
        "has_ocean_view": True,
        "is_furnished": True,
        "has_pool": True,
        "has_parking": True,
        "has_security": True,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": True,
        "is_new_construction": False,
        "has_balcony": True,
        "is_gated_community": True,
    },
    # --- NUEVAS: MARCANO ---
    {
        "title": "Townhouse Ranchos de Parguito 90m²",
        "municipality": Municipality.MARCANO,
        "zone": "Playa Parguito",
        "type": PropertyType.TOWNHOUSE,
        "price_usd": 49000,
        "bedrooms": 3,
        "bathrooms": 3,
        "area_m2": 90,
        "description": "Townhouse de 90m² en Ranchos de Parguito, frente al mar. 3 habitaciones, 2.5 baños, sala-comedor, cocina equipada, terraza con vista al mar. Urbanización cerrada con piscina y seguridad 24h. Ideal para vacaciones o alquiler turístico.",
        "features": ["vista al mar", "terraza", "piscina", "seguridad 24h", "frente al mar", "Ranchos de Parguito"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-7778888",
        "contact_email": "parguito@marcanorealty.com",
        "has_ocean_view": True,
        "is_furnished": False,
        "has_pool": True,
        "has_parking": True,
        "has_security": True,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": True,
        "is_new_construction": False,
        "has_balcony": True,
        "is_gated_community": True,
    },
    {
        "title": "Townhouse Casas del Guayamuri El Salado 160m²",
        "municipality": Municipality.MARCANO,
        "zone": "El Salado",
        "type": PropertyType.TOWNHOUSE,
        "price_usd": 48500,
        "bedrooms": 3,
        "bathrooms": 3,
        "area_m2": 160,
        "description": "Townhouse de 160m² en Casas del Guayamuri, El Salado. 3 habitaciones, 3 baños, sala de doble altura, cocina moderna, jardín privado. Garaje para 2 vehículos. Zona residencial tranquila cerca de Playa Parguito. Ideal para familia.",
        "features": ["sala doble altura", "jardín privado", "garaje 2 autos", "zona tranquila", "cerca de playa"],
        "status": PropertyStatus.AVAILABLE,
        "contact_phone": "+58 412-7778888",
        "contact_email": "parguito@marcanorealty.com",
        "has_ocean_view": False,
        "is_furnished": False,
        "has_pool": False,
        "has_parking": True,
        "has_security": False,
        "has_generator": False,
        "has_water_tank": False,
        "has_ac": False,
        "is_new_construction": False,
        "has_balcony": False,
        "is_gated_community": False,
    },
]


async def seed_properties() -> None:
    """Inserta propiedades y genera sus embeddings vectoriales."""
    llm = LLMClient()
    db = Database(settings.database_path, embedding_dim=llm.embedding_dim)
    await db.connect()

    repo = PropertyRepository(db)

    logger.info("seed_start", count=len(SEED_PROPERTIES))

    for data in SEED_PROPERTIES:
        prop = Property(**data)
        created = await repo.create(prop)
        logger.info("property_inserted", id=created.id, title=created.title)

        # Generar embedding de la descripción para búsqueda vectorial
        if created.id:
            embedding = await llm.embed(created.description)
            await db.vec_insert(
                table="property_embeddings",
                vector=embedding,
                vector_column="description_embedding",
                property_id=created.id,
            )
            logger.info("embedding_inserted", property_id=created.id)

    await db.commit()
    await db.close()
    logger.info("seed_complete")


if __name__ == "__main__":
    asyncio.run(seed_properties())
